### ISSUE TITLE
e2e-nvidia-l40s-x4.yml breaks when running on PRs

### ISSUE THREAD

**Issue by ktdreyer** [instructlab/training#598]
The [e2e-nvidia-l40s-x4.yml](https://github.com/instructlab/training/blob/main/.github/workflows/e2e-nvidia-l40s-x4.yml) action is supposed to comment on PRs when it runs.

However, it's breaking when it tries to add a "workflow launched" comment with the `gh` CLI. From [a recent run](https://github.com/instructlab/training/actions/runs/15449968658):

```
Run gh pr comment "594" -b "E2E (NVIDIA L40S x4) (python 3.11) workflow launched on this PR: [View run](https://github.com/instructlab/training/actions/runs/15449968658)"
  gh pr comment "594" -b "E2E (NVIDIA L40S x4) (python 3.11) workflow launched on this PR: [View run](https://github.com/instructlab/training/actions/runs/15449968658)"
  env:
    GH_TOKEN: ***
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TMPDIR: /home/tmp
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
```

**Comment by ktdreyer** [comment]
The yaml is mis-indented [here](https://github.com/instructlab/training/blob/2a1e9b61d68026618147eefd55e0ea17188b0ea5/.github/actions/run-e2e/action.yml#L91-L92), and the other two `gh pr comment` statements further on in `.github/actions/run-e2e/action.yml`.

```yaml
    - name: Add comment to PR
      if: steps.check_pr.outputs.is_pr == 'true'
      working-directory: ./training
      shell: bash
      run: |
        gh pr comment "${{ steps.check_pr.outputs.pr_or_branch }}" -b "${{ github.workflow }} workflow launched on this PR: [View run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          GH_TOKEN: ${{ inputs.gh-token }}
```

The `env` key needs to be at the same level as `run`.
